apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namesuffix: -plain
commonLabels:
  app: nginx-hello-plain

resources:
  - ../../base

images:
  - name: docker.io/nginxdemos/hello
    newTag: plain-text
