apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxdemo-hello
spec:
  template:
    spec:
      containers:
        - name: hello
          volumeMounts:
            - name: content
              mountPath: /usr/share/nginx/html
      volumes:
        - name: content
          configMap:
            name: content
