apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namesuffix: -newcontent
commonLabels:
  app: nginx-hello-newcontent

configMapGenerator:
  - name: content
    files:
      - index.html

resources:
  - ../../base

patches:
  - path: deployment_patch.yaml
